Added_Schemas
lakshay42jain/TaskManagementRails pull request #1
Opened 2023-08-21 08:47 UTC by lakshay42jain

2023-08-21 09:49 UTC, gagan93jtg requested changes

2023-08-21 09:49 UTC, gagan93jtg commented on test/fixtures/task_categories.yml
> +
don't use fixtures. Use factories (later when u start working on test cases)

2023-08-21 09:49 UTC, gagan93jtg commented on test/models/task_comment_test.rb
> +class TaskCommentTest < ActiveSupport::TestCase
add rspec right now or don't commit test files for now. Delete them after autogeneration. The default picked library is minitest and we don't use it.

2023-08-22 09:36 UTC, neeraj33negi commented on db/migrate/20230821083754_add_not_null_constraints_to_users.rb
> +    change_column_null :users, :email, false
what does this do? just curious

2023-08-22 09:36 UTC, neeraj33negi commented on db/migrate/20230821083659_create_tasks_task_categories.rb
> +      t.references :tasks, null: false, foreign_key: true
is this correct? should this be `t.references :task ...` ?

2023-08-22 09:36 UTC, neeraj33negi commented on db/migrate/20230821083532_create_tasks.rb
> +      t.references :assigned_user, null: false, foreign_key: true
did this migration run?

2023-08-22 09:36 UTC, neeraj33negi commented on db/migrate/20230821083532_create_tasks.rb
> +      t.integer :status
add default/initial values

2023-08-22 09:36 UTC, neeraj33negi commented on db/migrate/20230821083518_create_users.rb
> +      t.string :email
unique index

2023-08-22 09:36 UTC, neeraj33negi commented on config/database.yml
> +  database: TaskManagement_production
snake case

2023-08-22 09:36 UTC, neeraj33negi commented on app/models/task_comment.rb
> +end
I dont see has_many associations anywhere

2023-08-22 10:37 UTC, lakshay42jain commented on db/migrate/20230821083754_add_not_null_constraints_to_users.rb
> +    change_column_null :users, :email, false
email should not be null

2023-08-23 07:13 UTC, neeraj33negi requested changes

2023-08-23 07:13 UTC, neeraj33negi commented on app/models/task.rb
> +  validates :assigner_user_id, presence: true
these could be one liner, pls check how

2023-08-23 07:13 UTC, neeraj33negi commented on app/models/task.rb
> +  has_many :task_task_categories
add `dependent`

2023-08-23 07:13 UTC, neeraj33negi commented on app/models/task.rb
> +  enum status: {pending: 1, in_progress: 2, completed: 3}
space after and before `{` and `}`
add empty line after enum definition

2023-08-23 07:13 UTC, neeraj33negi commented on app/models/task_category.rb
> +  has_many :task_task_categories
dependent

2023-08-23 07:13 UTC, neeraj33negi commented on app/models/task_category.rb
> +class TaskCategory < ApplicationRecord
check if there should be validations here

2023-08-23 07:13 UTC, neeraj33negi commented on app/models/task.rb
> +  validates :assigner_user_id, presence: true
also check what other validations should be there

2023-08-23 07:13 UTC, neeraj33negi commented on app/models/task.rb
> +  belongs_to :user, foreign_key: 'assigner_user_id'
`belongs_to :user` twice? this is ambiguous, check how this could be improved

2023-08-23 07:13 UTC, neeraj33negi commented on app/models/user.rb
> +  validates :active, inclusion: { in: [true, false] }
is this needed?

2023-08-23 07:13 UTC, neeraj33negi commented on app/models/user.rb
> +  validates :active, inclusion: { in: [true, false] }
check all the validations that can be applied here

2023-08-24 04:27 UTC, neeraj33negi commented on app/models/task_category.rb
> +class TaskCategory < ApplicationRecord
read about `accepts_nested_attributes` and add validation for task_categories

2023-08-24 11:40 UTC, neeraj33negi commented on app/models/task.rb
> +  end
why is this here? also why are we hardcoding a db id in the code?

2023-08-24 11:40 UTC, neeraj33negi commented on app/models/task_task_category.rb
> +class TaskTaskCategory < ApplicationRecord
add a uniqness validation, there shud be just on entry in join table for a specific pair of task and task_category, read https://boringrails.com/tips/rails-unique-scope

2023-08-25 05:14 UTC, gagan93jtg requested changes

2023-08-25 05:14 UTC, gagan93jtg commented on app/models/task.rb
> +  belongs_to :assignee_user, class_name: 'User'
`assignee` and `assigner` are ok

2023-08-25 05:14 UTC, gagan93jtg commented on app/models/task.rb
> +  has_many :task_comments, dependent: :destroy
can we simply call them "comments"?

2023-08-25 05:14 UTC, gagan93jtg commented on app/models/task.rb
> +  has_many :task_categories, through: :task_task_categories
and `categories`?

2023-08-25 05:14 UTC, gagan93jtg commented on app/models/task.rb
> +      raise StandardError, 'Only admin can create the task'
why are we raising errors here? and why are we repeating strings in both lines?

2023-08-25 05:14 UTC, gagan93jtg commented on app/models/user.rb
> +  private
avoid private block. Use `private` with specific method if u want to declare as "private".

2023-08-25 07:25 UTC, PramanSatya approved these changes

2023-08-25 07:43 UTC, merged